name: kdg
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  pigment: ^1.0.3
  google_fonts: ^1.1.0
  adobe_xd: ^1.1.0+1
  cloud_firestore: ^0.16.0+1
  cloud_functions: ^0.9.0
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.15
  firebase_auth: ^0.20.1
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: ^0.2.3
  logger: ^0.9.4
  supercharged: ^2.0.0
  simple_animations: ^3.0.2
  parallax_image: ^0.3.1+1
  slimy_card: ^1.0.4
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  get: ^3.25.4
  loading: ^1.0.2
  curved_navigation_bar: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

