name: kdg
description: A family app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  badges: ^2.0.1
  circular_reveal_animation: ^2.0.0
  dotted_border: 
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  get: ^4.6.1
  getwidget: ^2.0.4
  glass_kit: ^2.0.1
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  font_awesome_flutter: ^10.1.0
  loading: ^1.0.2
  logger: ^0.9.4
  lottie: ^0.6.0
  material_design_icons_flutter: ^4.0.5955
  palette_generator: ^0.3.0
  parallax_image: ^0.3.1+1
  pigment: ^1.0.3
  provider: ^6.0.2
  share_plus:
  simple_animations: ^3.0.2
  slimy_card: ^1.0.4
  supercharged: ^2.1.1
  cloud_firestore: ^3.1.13
  firebase_auth: ^0.6.2+1
  firebase_storage: ^0.3.2
  cloud_functions: ^3.2.13
  firebase_messaging: ^11.2.15
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  fonts:
    - family: K2D
      fonts:
        - asset: fonts/K2D-Bold.ttf
        - asset: fonts/K2D-BoldItalic.ttf
          style: italic
