name: kdg
description: A family app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^2.1.0
  animated_clipper: ^0.2.0+2
  animated_loading_border: ^0.0.1
  animations: ^2.0.7
  badges: ^3.1.1
  capped_progress_indicator: ^0.0.2
  circular_reveal_animation: ^2.0.0
  cloud_firestore: ^4.8.4
  cloud_functions: ^4.3.4
  dotted_border: null
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_chat_ui: ^1.6.3
  flutter_easyloading: ^3.0.5
  flutter_slimy_card: null
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.1.0
  get: ^4.6.1
  getwidget: ^2.0.4
  glass_kit: ^2.0.1
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+1
  image_stack: ^2.1.1
  internet_connection_checker: ^0.0.1+4
  loading_indicator: ^3.1.0
  local_auth: ^2.1.0
  logger: ^1.1.0
  lottie: ^1.3.0
  material_design_icons_flutter: ^5.0.6595
  palette_generator: ^0.3.3
  pigment: ^1.0.3
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.10
  simple_animations: ^4.0.2
  sliding_up_panel: ^2.0.0+1
  supercharged: ^2.1.1
  swipe_deck: ^1.1.0
  syncfusion_flutter_datepicker: ^22.2.7
  syncfusion_flutter_pdfviewer: ^22.2.7
  uuid: ^3.0.7
  video_player: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  firebase_core_platform_interface: 4.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: K2D
      fonts:
        - asset: fonts/K2D-Bold.ttf
        - asset: fonts/K2D-BoldItalic.ttf
          style: italic
