name: kdg
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^1.1.0+1
  auto_animated: ^2.0.2
  # flutter_blurhash: ^0.6.0
  cached_network_image: ^2.3.3
  curved_navigation_bar: ^0.3.2
  cloud_firestore: ^1.0.1
  dio: ^4.0.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_analytics: ^7.1.1
  font_awesome_flutter: ^8.8.1
  get: ^4.0.0
  get_storage: ^2.0.0
  google_fonts: ^2.0.0
  parallax_image: ^0.3.1+1
  pigment: ^1.0.3
  provider: ^5.0.0
  slimy_card: ^1.0.4
  loading: ^1.0.2
  logger: ^0.9.4
  simple_animations: ^3.0.2
  supercharged: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

