name: kdg
description: A family app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  animated_clipper: ^0.2.0+2
  animations: ^2.0.1
  badges: ^2.0.1
  circular_reveal_animation: ^2.0.0
  cloud_firestore: ^3.1.13
  cloud_functions: ^3.2.13
  dotted_border: null
  fab_circular_menu: ^1.0.0
  file_picker: ^4.6.1
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.7.2
  firebase_messaging: ^11.2.15
  firebase_storage: ^10.2.14
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_chat_ui: ^1.6.3
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.1.0
  form_builder_file_picker: ^2.2.0
  get: ^4.6.1
  getwidget: ^2.0.4
  glass_kit: ^2.0.1
  google_fonts: ^2.3.2
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+1
  image_stack: ^2.1.1
  internet_connection_checker: ^0.0.1+4
  loading: ^1.0.2
  loading_indicator: ^3.1.0
  local_auth: ^2.1.0
  logger: ^1.1.0
  lottie: ^1.3.0
  material_design_icons_flutter: ^5.0.6595
  modal_bottom_sheet: ^2.0.1
  palette_generator: ^0.3.3
  parallax_image: ^0.3.1+1
  pigment: ^1.0.3
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  secure_application: ^3.8.0
  share_plus: ^4.0.10
  simple_animations: ^4.0.2
  sliding_up_panel: ^2.0.0+1
  slimy_card: ^1.0.4
  supercharged: ^2.1.1
  swipe_deck: ^1.1.0
  syncfusion_flutter_datepicker: ^20.2.36
  syncfusion_flutter_pdfviewer: ^20.1.56-beta
  uuid: ^3.0.7
  vibration: ^1.7.6
  video_player: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  fonts:
    - family: K2D
      fonts:
        - asset: fonts/K2D-Bold.ttf
        - asset: fonts/K2D-BoldItalic.ttf
          style: italic
