name: kdg
description: A family app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  badges: ^2.0.1
  circular_reveal_animation: ^2.0.0
  animated_clipper: ^0.2.0+2
  dotted_border:
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  get: ^4.6.1
  getwidget: ^2.0.4
  glass_kit: ^2.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^2.3.2
  fab_circular_menu: ^1.0.0
  google_sign_in: ^5.3.0
  font_awesome_flutter: ^10.1.0
  loading: ^1.0.2
  logger: ^1.1.0
  image_stack: ^2.1.1
  image_picker: ^0.8.5+1
  flutter_animated_dialog: ^2.0.1
  lottie: ^1.3.0
  material_design_icons_flutter: ^5.0.6595
  palette_generator: ^0.3.0
  parallax_image: ^0.3.1+1
  pigment: ^1.0.3
  provider: ^6.0.2
  share_plus:
  simple_animations: ^4.0.2
  slimy_card: ^1.0.4
  supercharged: ^2.1.1
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.16
  firebase_storage: ^10.2.14
  swipe_deck: ^1.1.0
  cloud_functions: ^3.2.13
  firebase_messaging: ^11.2.15
  video_player: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  fonts:
    - family: K2D
      fonts:
        - asset: fonts/K2D-Bold.ttf
        - asset: fonts/K2D-BoldItalic.ttf
          style: italic
