// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHNo-hvZs6mMbQQ73_VyYPSMk0QGPYLHg',
    appId: '1:464753026338:web:cac5bd16e3cab23faf317b',
    messagingSenderId: '464753026338',
    projectId: 'kdg3-6f07f',
    authDomain: 'kdg3-6f07f.firebaseapp.com',
    databaseURL: 'https://kdg3-6f07f.firebaseio.com',
    storageBucket: 'kdg3-6f07f.appspot.com',
    measurementId: 'G-S41WQZSC57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HITE_9esXxrTc4YSmIjg7yzP4LgSXw0',
    appId: '1:464753026338:android:b343336df19ca6b0af317b',
    messagingSenderId: '464753026338',
    projectId: 'kdg3-6f07f',
    databaseURL: 'https://kdg3-6f07f.firebaseio.com',
    storageBucket: 'kdg3-6f07f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYtPIupA14pU1S90InnI9WC9cuBQbqwAM',
    appId: '1:464753026338:ios:7fec333029e57218af317b',
    messagingSenderId: '464753026338',
    projectId: 'kdg3-6f07f',
    databaseURL: 'https://kdg3-6f07f.firebaseio.com',
    storageBucket: 'kdg3-6f07f.appspot.com',
    androidClientId: '464753026338-4k0gfc81m0hh1kktrg2bke86vcl9cru7.apps.googleusercontent.com',
    iosClientId: '464753026338-95iuj4lp42olpa6ceqgvneloe2u8dlf4.apps.googleusercontent.com',
    iosBundleId: 'com.jeydi.kdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYtPIupA14pU1S90InnI9WC9cuBQbqwAM',
    appId: '1:464753026338:ios:7fec333029e57218af317b',
    messagingSenderId: '464753026338',
    projectId: 'kdg3-6f07f',
    databaseURL: 'https://kdg3-6f07f.firebaseio.com',
    storageBucket: 'kdg3-6f07f.appspot.com',
    androidClientId: '464753026338-4k0gfc81m0hh1kktrg2bke86vcl9cru7.apps.googleusercontent.com',
    iosClientId: '464753026338-95iuj4lp42olpa6ceqgvneloe2u8dlf4.apps.googleusercontent.com',
    iosBundleId: 'com.jeydi.kdg',
  );
}
